services:
  - type: web
    name: tokfriends-admin-web
    env: node
    plan: free
    region: oregon
    rootDir: admin-web
    buildCommand: npm install && npm run build
    startCommand: npm run start -- -p $PORT
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: NEXT_PUBLIC_API_BASE_URL
        value: https://tokfriends-api.onrender.com
